[package]
name = "real-world-shuttle"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuttle-runtime = "0.15.0"
axum = "0.6.17"
shuttle-axum = "0.15.0"
tokio = "1.28.0"
